### ISSUE TITLE
Databinding has some problem: NoSuchMethodError: android.databinding.BindingBuildInfo.enableDebugLogs()Z

### ISSUE THREAD

**Issue by YouZiQian** [evant/binding-collection-adapter#79]
When I upgrade BindingCollectionAdapter to 2.1.0 this problem has occurred.
Sync project can be succeessful, but make and run will be failed;

here is the ErrorMessage.
![tim 20170427175926](https://cloud.githubusercontent.com/assets/8923844/25478407/822cba0a-2b73-11e7-8087-e4ca3eac07d1.png)
 
and my gradle plugin version is 2.3.1
![image](https://cloud.githubusercontent.com/assets/8923844/25478431/96e29c1c-2b73-11e7-9c11-ab4559b12b6e.png)

**Comment by evant** [comment]
Can you try running with `--stacktrace`?

**Comment by YouZiQian** [comment]
I've tried running with `--stacktrace`
this is the log:

`C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderFragment.java:17: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.FragmentMainOrderBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderFragment.java:27: 错误: 找不到符号
public class OrderFragment extends DatabindingFragment<FragmentMainOrderBinding> implements ViewPager.OnPageChangeListener {
                                                       ^
  符号: 类 FragmentMainOrderBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderItemViewModel.java:7: 错误: 程序包com.apt不存在
import com.apt.XRouter;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderListFragment.java:6: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.FragmentOrderBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderListFragment.java:13: 错误: 找不到符号
public class OrderListFragment extends DatabindingFragment<FragmentOrderBinding> {
                                                           ^
  符号: 类 FragmentOrderBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderViewModel.java:7: 错误: 程序包com.apt不存在
import com.apt.ApiFactory;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\fragment\OrderViewModel.java:8: 错误: 找不到符号
import com.lisong.tb.BR;
                    ^
  符号:   类 BR
  位置: 程序包 com.lisong.tb
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\MainActivity.java:14: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityMainBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\MainActivity.java:31: 错误: 找不到符号
public class MainActivity extends BaseFragmentActivity<ActivityMainBinding> {
                                                       ^
  符号: 类 ActivityMainBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\MessageActivity.java:8: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityMessageBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\MessageActivity.java:11: 错误: 找不到符号
public class MessageActivity extends BaseActivity<ActivityMessageBinding> {
                                                  ^
  符号: 类 ActivityMessageBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\MessageViewModel.java:7: 错误: 找不到符号
import com.lisong.tb.BR;
                    ^
  符号:   类 BR
  位置: 程序包 com.lisong.tb
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\order\OrderDetailActivity.java:12: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityOrderDetailBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\main\order\OrderDetailActivity.java:15: 错误: 找不到符号
public class OrderDetailActivity extends BaseActivity<ActivityOrderDetailBinding> {
                                                      ^
  符号: 类 ActivityOrderDetailBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\personal\PersonalActivity.java:7: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityPersonalBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\personal\PersonalActivity.java:10: 错误: 找不到符号
public class PersonalActivity extends BaseActivity<ActivityPersonalBinding> {
                                                   ^
  符号: 类 ActivityPersonalBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\SplashActivity.java:3: 错误: 程序包com.apt不存在
import com.apt.XRouter;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\SplashActivity.java:7: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivitySplashBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\SplashActivity.java:14: 错误: 找不到符号
public class SplashActivity extends BaseActivity<ActivitySplashBinding> {
                                                 ^
  符号: 类 ActivitySplashBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\LoginActivity.java:4: 错误: 程序包com.apt不存在
import com.apt.XRouter;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\LoginActivity.java:9: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityLoginBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\LoginActivity.java:13: 错误: 找不到符号
public class LoginActivity extends BaseActivity<ActivityLoginBinding> {
                                                ^
  符号: 类 ActivityLoginBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\LoginViewModel.java:6: 错误: 程序包com.apt不存在
import com.apt.ApiFactory;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\LoginViewModel.java:7: 错误: 程序包com.apt不存在
import com.apt.XRouter;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\PickRoleActivity.java:7: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityPickRoleBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\PickRoleActivity.java:10: 错误: 找不到符号
public class PickRoleActivity extends BaseActivity<ActivityPickRoleBinding> {
                                                   ^
  符号: 类 ActivityPickRoleBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\RegisterActivity.java:8: 错误: 程序包com.lisong.tb.databinding不存在
import com.lisong.tb.databinding.ActivityRegisterBinding;
                                ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\RegisterActivity.java:11: 错误: 找不到符号
public class RegisterActivity extends BaseActivity<ActivityRegisterBinding> {
                                                   ^
  符号: 类 ActivityRegisterBinding
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\ui\start\RegisterViewModel.java:7: 错误: 程序包com.apt不存在
import com.apt.ApiFactory;
              ^
C:\AndroidProjects\TB\app\src\main\java\com\lisong\tb\util\InstanceUtil.java:4: 错误: 程序包com.apt不存在
import com.apt.InstanceFactory;
              ^
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                ^
  符号:   方法 modulePackage()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                         ^
  符号:   方法 sdkRoot()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                                                 ^
  符号:   方法 layoutInfoDir()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                                                                                                                                                  ^
  符号:   方法 exportClassListTo()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                                                                                                                                                               ^
  符号:   方法 isLibrary()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                                                                                                                                                                            ^
  符号:   方法 minSdk()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                                                                                                                                                                                               ^
  符号:   方法 enableDebugLogs()
  位置: @interface BindingBuildInfo
C:\AndroidProjects\TB\app\build\generated\source\dataBinding\debug\android\databinding\layouts\DataBindingInfo.java:5: 错误: 找不到符号
@BindingBuildInfo(buildId="fb35211b-b18c-4b5d-856f-ffc293764b42", modulePackage="com.lisong.tb", sdkRoot="C:\\sdk",layoutInfoDir="C:\\AndroidProjects\\TB\\app\\build\\intermediates\\data-binding-info\\debug",exportClassListTo="",isLibrary=false,minSdk=21,enableDebugLogs=false,printEncodedError=true)
                                                                                                                                                                                                                                                                                                       ^
  符号:   方法 printEncodedError()
  位置: @interface BindingBuildInfo
注: 正在处理: com.lisong.tb.net.api.ApiService

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: android.databinding.BindingBuildInfo.enableDebugLogs()Z

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: android.databinding.BindingBuildInfo.enableDebugLogs()Z
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more
Caused by: java.lang.NoSuchMethodError: android.databinding.BindingBuildInfo.enableDebugLogs()Z
	at android.databinding.annotationprocessor.BuildInfoUtil.load(BuildInfoUtil.java:35)
	at android.databinding.annotationprocessor.ProcessDataBinding.process(ProcessDataBinding.java:59)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 39 more


BUILD FAILED

Total time: 6.186 secs`

**Comment by YouZiQian** [comment]
@evant

**Comment by evant** [comment]
Sorry for takeing a while to reply. The error implies databinding is missing the `enableDebugLogs` method on the `BindingBuildInfo` annotation. Are you _sure_ you are on `2.3.0+`?

**Comment by YouZiQian** [comment]
yes, I'm pretty sure the gradle plugin version is `2.3.1`

**Comment by YouZiQian** [comment]
I tried reenable databinding and use ` classpath 'com.android.tools.build:gradle:2.3.0'` , but doesn't work .

**Comment by YouZiQian** [comment]
is anyone here?  @evant

**Comment by anubiann00b** [comment]
I'm having the same issue with databinding in general, not this library. It compiles fine without proguard but once I turn on proguard it doesn't work.

**Comment by evant** [comment]
Closing for lack of response, fell free to re-open if you are still having issues.

**Comment by Prusinowsky** [comment]
I have the same issue.
